mode:
  develop: true

server:
  port: 8090

db:
  dsn: root:123456@tcp(192.168.12.133:3306)/gofly?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 10 # 最多空闲连接数
  maxOpenConn: 10 # 最多打开连接数

redis:
  url: 192.168.12.133:6379
jwt:
  signingKey: conan.com
  tokenExpire: 3  # token有效时长(分钟)

log:
  MaxSize: 100      # 日志文件最大的尺寸(M), 超限后开始自动分割
  MaxBackups: 10  # 保留旧文件的最大个数
  MaxAge: 30      # 保留旧文件的最大天数

ansible:
  user:
    name: root
    password: 123456
  ShutdownHost:
    Args: "poweroff"